[package]
name = "invidious"
version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo = { workspace = true }
reqwasm = { workspace = true }
csv = { workspace = true }
ron = { workspace = true }
futures = { workspace = true }
rustytube-error = { workspace = true }
utils = { workspace = true }
serde-xml-rs = { workspace = true }

wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }

[dependencies.web-sys]
workspace = true
features = [
    'Headers',
    'Request',
    'RequestInit',
    'RequestMode',
    'Response',
    'Window',
    'Performance',
    "MediaSource"
]

[dependencies.serde]
workspace = true
features = ["derive"]

[dependencies.serde_json]
workspace = true

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
wasm-bindgen-cli = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }

[dev-dependencies.web-sys]
workspace = true